databases:
  - name: buybase
    databaseName: buybase
    user: buybase

services:
  - type: web
    name: buybase
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: buybase
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false